[profile.default]
src = "contracts"
out = "out"
libs = ["../../lib", "../../contracts/src"]
test = "tests"
ffi = true
fs_permissions = [{ access = "read-write", path = "./tests/benchmarks"}]

[fuzz]
runs = 10
seed = '0x1234' 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
