[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "../../contracts", "../../lib"]
test = "tests"
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
